In [2]:
miles = 1820
gallons = 97
mpg = miles / gallons
print(mpg)

18.762886597938145


In [6]:
print(mpg)

18.762886597938145


# Intro to Numpy 
## importing a library

as np = Is an alias. So that is what we are going to refer to numpy as

In [17]:
import numpy as np
gert = np.array([1, 2, 3, 4])

In [5]:
gert

array([1, 2, 3, 4])

In [10]:
gert_2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [11]:
gert_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Other ways to create arrays

In [13]:
gumbo = [x for x in range(10)]

In [14]:
gumbo

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
gumbo_2D = [[x + y * 10 for x in range(10)] for y in range(10)]
gumbo_2D

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

## In Numpy

In [19]:
## numpy is already imported, so don't need to repeat
wonton = np.arange(100)
wonton

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
wonton.reshape([10,10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
wonton[3]

3

In [26]:
gumbo_2D[7][2]

72

## Comparing Numpy and Python
### Speed

In [28]:
%time pyT1 = [[x + y * 1000 for x in range(1000)] for y in range (1000)]

CPU times: user 97.5 ms, sys: 20.9 ms, total: 118 ms
Wall time: 120 ms


In [30]:
%time npT1 = np.arange(1000000).reshape((1000, 1000))

CPU times: user 2.81 ms, sys: 0 ns, total: 2.81 ms
Wall time: 2.36 ms


## Add 1 to each element
## Python

In [42]:
## this is a 2D array 
def add1():
  for i in range(5):
    for j in range(5):
      pyT1[i][j] = pyT1[i][j] + 1
      # print(pyT1[i][j])
%time add1()


CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 51 µs


In [33]:
%time npT1 + 1

CPU times: user 3.22 ms, sys: 3.08 ms, total: 6.3 ms
Wall time: 8.27 ms


array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

## Numpy Functions

In [34]:
npT1.sum()

499999500000